services:
  # Web service
  - type: web
    name: guard-on
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: guard-on-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  # PostgreSQL Database
  - type: postgres
    name: guard-on-db
    plan: free
    ipAllowList: []