services:
  # Web service
  - type: web
    name: guard-on
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  # Optional PostgreSQL Database - enable this if you don't have an external database
  # - type: pserv
  #   name: guard-on-db
  #   plan: free
  #   env: docker
  #   disk:
  #     name: data
  #     mountPath: /var/lib/postgresql/data
  #     sizeGB: 10